In [19]:
import numpy as np
import pandas as pd
import keras
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras.models as km
from keras.models import Sequential
from keras import activations, initializers, regularizers, constraints
from keras.layers import Dense, Activation

In [20]:
dataset = pd.read_csv("concrete_strength.csv")

In [21]:
dataset

,cement,blast_furnace_slag,fly_ash,water,superplasticizer,coarse_aggregate,fine_aggregate,age,compressive_strength
0,440.54,201.69,189.08,233.73,30.43,1027.16,604.76,56,67.22
1,293.11,258.40,53.16,239.09,25.54,830.35,802.18,28,40.17
2,477.78,182.71,100.81,230.53,28.39,963.51,916.18,365,74.72
3,406.84,325.64,18.14,245.40,12.33,874.98,855.55,180,55.36
4,141.44,150.53,84.73,180.51,31.89,821.65,669.77,365,40.41
...,...,...,...,...,...,...,...,...,...
1025,233.09,172.25,63.26,154.82,26.72,1141.77,751.74,1,28.96
1026,516.92,351.12,41.05,196.64,28.67,1043.84,808.60,56,73.86
1027,261.19,170.48,90.72,232.47,15.47,923.92,606.29,14,27.77
1028,424.94,47.00,109.36,161.34,28.62,928.17,659.81,180,65.08
1029,277.38,18.57,183.82,182.86,8.86,948.62,840.59,180,46.12

In [22]:
dataset.describe()

,cement,blast_furnace_slag,fly_ash,water,superplasticizer,coarse_aggregate,fine_aggregate,age,compressive_strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,319.245184,181.078184,99.453379,184.159068,15.480476,967.539883,791.674777,83.355340,42.975757
std,128.106970,104.235999,57.601170,37.503989,9.052507,100.383751,113.826685,115.917081,17.839636
min,100.540000,0.190000,0.200000,120.080000,0.030000,800.110000,590.380000,1.000000,2.000000
25%,206.230000,88.312500,49.450000,152.535000,7.587500,878.170000,694.227500,7.000000,31.030000
50%,317.720000,176.865000,100.165000,184.400000,15.265000,963.690000,793.580000,28.000000,44.295000
75%,433.672500,273.882500,149.597500,215.532500,23.220000,1054.767500,885.417500,90.000000,56.225000
max,539.610000,358.790000,199.950000,249.920000,31.990000,1144.610000,991.810000,365.000000,82.000000

In [23]:
X = dataset.drop(columns=["compressive_strength"])
y = dataset["compressive_strength"]

In [24]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=123)

In [25]:
sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)

In [26]:
train_X.shape

(721, 8)

In [27]:
model = Sequential()
model.add(Dense(units=8, kernel_initializer='uniform', activation='relu', input_dim=8))
model.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
model.add(Dense(units=4, kernel_initializer='uniform', activation='relu'))
model.add(Dense(units=1, kernel_initializer='uniform', activation='linear'))

f:\Deep_Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 6)              │            54 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 4)              │            28 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 159 (636.00 B)

 Trainable params: 159 (636.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [30]:
print(train_X.shape)
print(train_y.shape)

(721, 8)
(721,)

In [31]:
history = model.fit(train_X, train_y, validation_data=(test_X, test_y), epochs=50, batch_size=32)

Epoch 1/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 9s 26ms/step - loss: 2155.5930 - val_loss: 2181.7024
Epoch 2/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2153.0466 - val_loss: 2178.7312
Epoch 3/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2149.4475 - val_loss: 2174.1562
Epoch 4/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2143.3982 - val_loss: 2165.9326
Epoch 5/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2132.3174 - val_loss: 2150.6892
Epoch 6/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2111.9304 - val_loss: 2122.9912
Epoch 7/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2076.1260 - val_loss: 2076.0930
Epoch 8/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2017.2769 - val_loss: 2001.3633
Epoch 9/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1927.4518 - val_loss: 1889.8781
Epoch 10/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1799.0692 - val_loss: 1736.3369
Epoch 11/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 1627.0020 - val_loss: 1537.2739
Epoch 12/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 1409.6124 - val_loss: 1297.3969
Epoch 13/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 1158.7651 - val_loss: 1027.8958
Epoch 14/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 891.1091 - val_loss: 754.7375
Epoch 15/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 632.3860 - val_loss: 511.8463
Epoch 16/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 417.5512 - val_loss: 323.7466
Epoch 17/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 264.6318 - val_loss: 205.3046
Epoch 18/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 176.3703 - val_loss: 139.4501
Epoch 19/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 129.7014 - val_loss: 109.1162
Epoch 20/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 107.0063 - val_loss: 93.4786
Epoch 21/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 93.9846 - val_loss: 84.4418
Epoch 22/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.7511 - val_loss: 78.6715
Epoch 23/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 79.8090 - val_loss: 74.7542
Epoch 24/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 75.6907 - val_loss: 71.9020
Epoch 25/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 72.8963 - val_loss: 69.5158
Epoch 26/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 70.6526 - val_loss: 68.0023
Epoch 27/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 69.1047 - val_loss: 66.7463
Epoch 28/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 67.9532 - val_loss: 65.5746
Epoch 29/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 66.9267 - val_loss: 64.9275
Epoch 30/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 66.1555 - val_loss: 64.0667
Epoch 31/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 65.5766 - val_loss: 63.3036
Epoch 32/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 64.9511 - val_loss: 62.8724
Epoch 33/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 64.4215 - val_loss: 62.4772
Epoch 34/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 64.0083 - val_loss: 61.8318
Epoch 35/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 63.5105 - val_loss: 61.4083
Epoch 36/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 63.1389 - val_loss: 61.1721
Epoch 37/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 62.7334 - val_loss: 60.7890
Epoch 38/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 62.3112 - val_loss: 60.5410
Epoch 39/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 61.9978 - val_loss: 60.1670
Epoch 40/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 61.6490 - val_loss: 59.8122
Epoch 41/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 61.2187 - val_loss: 59.4871
Epoch 42/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 60.9407 - val_loss: 59.1774
Epoch 43/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 60.6394 - val_loss: 58.8417
Epoch 44/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 60.3720 - val_loss: 58.6802
Epoch 45/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 60.0698 - val_loss: 58.3820
Epoch 46/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 59.7162 - val_loss: 58.0419
Epoch 47/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 59.4239 - val_loss: 57.8342
Epoch 48/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 59.2056 - val_loss: 57.6336
Epoch 49/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 58.9175 - val_loss: 57.4179
Epoch 50/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 58.6860 - val_loss: 57.1337

In [32]:
predictions = model.predict(test_X)
predictions

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

array([[53.29121 ],
       [57.24161 ],
       [51.988503],
       [37.629284],
       [34.88553 ],
       [39.230667],
       [44.07798 ],
       [59.836823],
       [28.677984],
       [55.888035],
       [59.52144 ],
       [50.377014],
       [58.546448],
       [62.491833],
       [28.810202],
       [65.54813 ],
       [56.389797],
       [59.453865],
       [32.914917],
       [14.462221],
       [58.520805],
       [62.800377],
       [51.970142],
       [35.931587],
       [56.569107],
       [16.040688],
       [28.891378],
       [15.782362],
       [37.921165],
       [40.93438 ],
       [28.180433],
       [44.13326 ],
       [19.697336],
       [50.37859 ],
       [37.768494],
       [49.408806],
       [18.8799  ],
       [63.426136],
       [20.277445],
       [68.06183 ],
       [27.35134 ],
       [46.181396],
       [45.040222],
       [44.51067 ],
       [42.297314],
       [74.4656  ],
       [44.328827],
       [24.98086 ],
       [26.12423 ],
       [63.634056],
       [26.261545],
       [72.82117 ],
       [35.794193],
       [20.429815],
       [29.572256],
       [47.462124],
       [22.28549 ],
       [55.98107 ],
       [67.018745],
       [51.100548],
       [75.5043  ],
       [49.743813],
       [46.7495  ],
       [34.721786],
       [66.63159 ],
       [87.53066 ],
       [35.155434],
       [33.483093],
       [80.387665],
       [60.36222 ],
       [21.188433],
       [47.65387 ],
       [35.63671 ],
       [34.92226 ],
       [39.57674 ],
       [54.805313],
       [38.11309 ],
       [63.66741 ],
       [42.748703],
       [26.178371],
       [37.158802],
       [47.126884],
       [34.510315],
       [45.844154],
       [11.404465],
       [28.741714],
       [56.108044],
       [24.682276],
       [42.76317 ],
       [17.036432],
       [57.44066 ],
       [65.63449 ],
       [63.546318],
       [56.431133],
       [45.41145 ],
       [20.675545],
       [55.94378 ],
       [54.40183 ],
       [54.491013],
       [48.508904],
       [44.932384],
       [37.228466],
       [35.259174],
       [28.11191 ],
       [53.55935 ],
       [12.511965],
       [22.963491],
       [54.862904],
       [62.736298],
       [14.332331],
       [55.570152],
       [43.042892],
       [12.723897],
       [42.52353 ],
       [42.794937],
       [34.0445  ],
       [54.71987 ],
       [24.736097],
       [41.771957],
       [31.874819],
       [66.32628 ],
       [36.432568],
       [60.82135 ],
       [54.160946],
       [45.69583 ],
       [47.914497],
       [24.029799],
       [11.238729],
       [16.319288],
       [61.855415],
       [30.408068],
       [49.2319  ],
       [42.457264],
       [43.84324 ],
       [35.180897],
       [21.981264],
       [35.544594],
       [26.437506],
       [26.249449],
       [45.925003],
       [51.129295],
       [52.367867],
       [50.808407],
       [22.973192],
       [40.606323],
       [19.614828],
       [54.151386],
       [14.542948],
       [21.232916],
       [78.509   ],
       [63.307137],
       [42.924683],
       [49.15393 ],
       [79.0022  ],
       [34.478172],
       [58.257366],
       [47.59051 ],
       [28.507347],
       [49.16356 ],
       [60.92148 ],
       [30.385536],
       [33.792328],
       [30.010622],
       [70.33435 ],
       [57.626152],
       [45.46054 ],
       [59.266098],
       [31.54279 ],
       [20.655247],
       [59.19095 ],
       [36.009888],
       [22.846024],
       [68.33539 ],
       [36.252735],
       [25.854574],
       [62.565292],
       [32.32739 ],
       [18.306677],
       [53.927235],
       [13.89094 ],
       [56.742317],
       [84.312256],
       [64.582596],
       [50.673218],
       [47.46326 ],
       [20.26649 ],
       [16.038887],
       [34.3259  ],
       [65.1306  ],
       [38.150597],
       [23.868181],
       [58.64566 ],
       [35.224995],
       [33.717987],
       [61.56356 ],
       [20.437214],
       [25.385618],
       [20.847326],
       [29.51135 ],
       [24.553328],
       [61.766685],
       [45.251755],
       [15.501605],
       [40.22082 ],
       [47.393944],
       [62.702854],
       [33.052334],
       [69.44739 ],
       [66.289215],
       [29.545532],
       [39.537918],
       [38.344524],
       [72.49527 ],
       [38.101467],
       [53.916603],
       [44.17112 ],
       [54.947556],
       [46.271774],
       [36.485336],
       [48.695335],
       [46.175205],
       [42.715046],
       [82.16176 ],
       [54.097725],
       [63.82566 ],
       [37.880226],
       [19.998447],
       [25.217611],
       [32.56932 ],
       [47.708794],
       [80.005165],
       [45.880142],
       [53.00392 ],
       [38.930332],
       [38.10685 ],
       [34.626392],
       [30.313921],
       [26.778692],
       [17.723387],
       [44.80957 ],
       [26.357756],
       [28.817781],
       [46.788456],
       [31.878958],
       [44.52984 ],
       [24.197985],
       [25.107126],
       [56.09501 ],
       [28.797777],
       [65.206245],
       [56.835598],
       [39.99953 ],
       [57.991364],
       [14.435652],
       [63.280334],
       [51.508606],
       [76.57242 ],
       [41.656578],
       [61.326035],
       [39.748314],
       [45.940586],
       [53.92346 ],
       [11.204813],
       [27.966745],
       [41.285694],
       [24.886808],
       [26.954931],
       [54.83748 ],
       [40.800484],
       [20.378727],
       [65.47802 ],
       [65.578705],
       [50.615578],
       [75.22006 ],
       [26.441278],
       [31.669315],
       [25.74682 ],
       [69.20528 ],
       [62.240112],
       [73.79471 ],
       [43.287796],
       [29.872559],
       [31.960512],
       [54.139153],
       [23.289349],
       [27.273924],
       [29.141241],
       [19.217806],
       [39.430153],
       [60.280983],
       [48.59433 ],
       [27.389397],
       [28.199545],
       [26.946875],
       [25.707956],
       [26.333117],
       [53.80478 ],
       [26.283216],
       [55.649426],
       [31.969133],
       [44.225315],
       [19.737629],
       [30.911203],
       [58.89049 ],
       [41.61873 ],
       [46.5995  ],
       [22.725622],
       [37.63043 ],
       [61.585117]], dtype=float32)

In [33]:
from sklearn.metrics import mean_squared_error, r2_score
print("MSE:", mean_squared_error(test_y, predictions))
print("R2 Score:", r2_score(test_y, predictions))

MSE: 57.133748391194274
R2 Score: 0.8245092293259267

In [34]:
import pickle

# Model save karein
model.save("concrete_model.h5")

# Scaler (sc) ko pickle me save karein
with open("scaler.pkl", "wb") as f:
    pickle.dump(sc, f)

print("Model aur Scaler dono successfully save ho gaye!")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model aur Scaler dono successfully save ho gaye!