In [1]:
import numpy as np
import pandas as pd
import keras
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras.models as km
from keras.models import Sequential
from keras import activations, initializers, regularizers, constraints
from keras.layers import Dense, Activation

KeyboardInterrupt:

In [ ]:
dataset = pd.read_csv("concrete_strength.csv")

In [ ]:
dataset

,cement,blast_furnace_slag,fly_ash,water,superplasticizer,coarse_aggregate,fine_aggregate,age,compressive_strength
0,440.54,201.69,189.08,233.73,30.43,1027.16,604.76,56,67.22
1,293.11,258.40,53.16,239.09,25.54,830.35,802.18,28,40.17
2,477.78,182.71,100.81,230.53,28.39,963.51,916.18,365,74.72
3,406.84,325.64,18.14,245.40,12.33,874.98,855.55,180,55.36
4,141.44,150.53,84.73,180.51,31.89,821.65,669.77,365,40.41
...,...,...,...,...,...,...,...,...,...
1025,233.09,172.25,63.26,154.82,26.72,1141.77,751.74,1,28.96
1026,516.92,351.12,41.05,196.64,28.67,1043.84,808.60,56,73.86
1027,261.19,170.48,90.72,232.47,15.47,923.92,606.29,14,27.77
1028,424.94,47.00,109.36,161.34,28.62,928.17,659.81,180,65.08
1029,277.38,18.57,183.82,182.86,8.86,948.62,840.59,180,46.12

In [ ]:
dataset.describe()

,cement,blast_furnace_slag,fly_ash,water,superplasticizer,coarse_aggregate,fine_aggregate,age,compressive_strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,319.245184,181.078184,99.453379,184.159068,15.480476,967.539883,791.674777,83.355340,42.975757
std,128.106970,104.235999,57.601170,37.503989,9.052507,100.383751,113.826685,115.917081,17.839636
min,100.540000,0.190000,0.200000,120.080000,0.030000,800.110000,590.380000,1.000000,2.000000
25%,206.230000,88.312500,49.450000,152.535000,7.587500,878.170000,694.227500,7.000000,31.030000
50%,317.720000,176.865000,100.165000,184.400000,15.265000,963.690000,793.580000,28.000000,44.295000
75%,433.672500,273.882500,149.597500,215.532500,23.220000,1054.767500,885.417500,90.000000,56.225000
max,539.610000,358.790000,199.950000,249.920000,31.990000,1144.610000,991.810000,365.000000,82.000000

In [ ]:
X = dataset.drop(columns=["compressive_strength"])
y = dataset["compressive_strength"]

In [ ]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=123)

In [ ]:
# sc = StandardScaler()
# train_X = sc.fit_transform(train_X)
# test_X = sc.transform(test_X)

In [ ]:
train_X.shape

(721, 8)

In [ ]:
model = Sequential()
model.add(Dense(units=8, kernel_initializer='uniform', activation='relu', input_dim=8))
model.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
model.add(Dense(units=4, kernel_initializer='uniform', activation='relu'))
model.add(Dense(units=1, kernel_initializer='uniform', activation='linear'))

f:\Deep_Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │            54 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 4)              │            28 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 159 (636.00 B)

 Trainable params: 159 (636.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='mean_squared_error', optimizer='adam')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [ ]:
print(train_X.shape)
print(train_y.shape)

(721, 8)
(721,)

In [ ]:
history = model.fit(train_X, train_y, validation_data=(test_X, test_y), epochs=50, batch_size=32)

Epoch 1/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 6s 57ms/step - loss: 2151.0374 - val_loss: 2164.8601
Epoch 2/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 2088.3047 - val_loss: 2006.9304
Epoch 3/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 1722.7612 - val_loss: 1314.1636
Epoch 4/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 765.1122 - val_loss: 284.4011
Epoch 5/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 263.8420 - val_loss: 245.9406
Epoch 6/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 237.8931 - val_loss: 236.3407
Epoch 7/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 227.3721 - val_loss: 228.8705
Epoch 8/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 220.8681 - val_loss: 221.4938
Epoch 9/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 213.2387 - val_loss: 214.5492
Epoch 10/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 206.2408 - val_loss: 207.1425
Epoch 11/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 199.1266 - val_loss: 199.4907
Epoch 12/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 191.9506 - val_loss: 191.8462
Epoch 13/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 184.0727 - val_loss: 183.7076
Epoch 14/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 175.8072 - val_loss: 176.0822
Epoch 15/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 168.1999 - val_loss: 167.7391
Epoch 16/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 159.9376 - val_loss: 159.1496
Epoch 17/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 151.6155 - val_loss: 150.4469
Epoch 18/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 143.0510 - val_loss: 142.3497
Epoch 19/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 135.2959 - val_loss: 133.3204
Epoch 20/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 126.5173 - val_loss: 124.6744
Epoch 21/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 117.5499 - val_loss: 115.6045
Epoch 22/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 110.1507 - val_loss: 107.6183
Epoch 23/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 101.5552 - val_loss: 99.5141
Epoch 24/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 94.1513 - val_loss: 91.7291
Epoch 25/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 87.3260 - val_loss: 84.3917
Epoch 26/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 81.0557 - val_loss: 79.1244
Epoch 27/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 76.0293 - val_loss: 73.6665
Epoch 28/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 71.8174 - val_loss: 69.1649
Epoch 29/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 67.9714 - val_loss: 66.7512
Epoch 30/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 65.5444 - val_loss: 63.2333
Epoch 31/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 63.5947 - val_loss: 61.1552
Epoch 32/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 61.6778 - val_loss: 59.8966
Epoch 33/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 60.3949 - val_loss: 58.6585
Epoch 34/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 59.7558 - val_loss: 57.4460
Epoch 35/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 59.0957 - val_loss: 57.4714
Epoch 36/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 58.9456 - val_loss: 55.8169
Epoch 37/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 57.2503 - val_loss: 55.2954
Epoch 38/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 56.9995 - val_loss: 57.8607
Epoch 39/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - loss: 56.7204 - val_loss: 53.7108
Epoch 40/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 56.1851 - val_loss: 53.8352
Epoch 41/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 55.7017 - val_loss: 52.6254
Epoch 42/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 54.9986 - val_loss: 52.2087
Epoch 43/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 54.4144 - val_loss: 51.7626
Epoch 44/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 54.5652 - val_loss: 51.2828
Epoch 45/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 53.8690 - val_loss: 52.7015
Epoch 46/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 53.4725 - val_loss: 50.5432
Epoch 47/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 53.4147 - val_loss: 49.6341
Epoch 48/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 52.3596 - val_loss: 49.4803
Epoch 49/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 52.9428 - val_loss: 49.1219
Epoch 50/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 52.0899 - val_loss: 48.3567

In [ ]:
predictions = model.predict(test_X)
predictions

10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step

array([[45.495075],
       [60.280544],
       [51.733738],
       [44.32413 ],
       [40.493366],
       [25.311918],
       [49.47425 ],
       [62.67638 ],
       [22.271385],
       [57.1206  ],
       [56.46694 ],
       [53.097767],
       [56.86745 ],
       [64.3759  ],
       [30.72546 ],
       [61.80315 ],
       [51.523106],
       [61.33008 ],
       [35.041393],
       [17.98591 ],
       [56.137577],
       [62.846737],
       [56.75091 ],
       [31.8645  ],
       [51.010258],
       [14.044122],
       [31.396128],
       [22.620504],
       [36.0666  ],
       [39.541508],
       [20.489985],
       [43.617054],
       [19.427341],
       [44.875774],
       [28.876268],
       [56.89172 ],
       [17.035852],
       [67.52673 ],
       [23.724424],
       [74.96853 ],
       [33.097164],
       [46.300602],
       [41.272194],
       [46.772083],
       [32.919197],
       [68.51241 ],
       [44.82883 ],
       [30.082556],
       [32.414078],
       [63.15843 ],
       [29.252565],
       [71.604   ],
       [30.091982],
       [30.194796],
       [36.90946 ],
       [52.45724 ],
       [19.382805],
       [57.687874],
       [69.91636 ],
       [54.498646],
       [74.30959 ],
       [50.837997],
       [52.156956],
       [21.396357],
       [65.55577 ],
       [81.81588 ],
       [36.944454],
       [33.124527],
       [74.81336 ],
       [56.026966],
       [16.949419],
       [50.88446 ],
       [45.299507],
       [38.556538],
       [44.516323],
       [54.63399 ],
       [44.84534 ],
       [53.93993 ],
       [36.14509 ],
       [30.402498],
       [38.606503],
       [48.65486 ],
       [36.40659 ],
       [44.424747],
       [14.062539],
       [31.561611],
       [41.871304],
       [27.4139  ],
       [46.151505],
       [19.57758 ],
       [53.708286],
       [63.761448],
       [64.61121 ],
       [56.609035],
       [48.721508],
       [19.769129],
       [52.44356 ],
       [52.435867],
       [59.125896],
       [44.396847],
       [43.412663],
       [37.42671 ],
       [33.904026],
       [29.671171],
       [50.206837],
       [15.862893],
       [22.351965],
       [50.02514 ],
       [61.688694],
       [16.4243  ],
       [55.740116],
       [39.637104],
       [16.81734 ],
       [47.452946],
       [46.79735 ],
       [37.86879 ],
       [60.969364],
       [26.76034 ],
       [42.05068 ],
       [28.387522],
       [66.75817 ],
       [38.5564  ],
       [58.456413],
       [53.83682 ],
       [50.493816],
       [50.98087 ],
       [26.76113 ],
       [14.588067],
       [11.026728],
       [58.29111 ],
       [26.558912],
       [46.802723],
       [42.319714],
       [36.035736],
       [38.960964],
       [16.973265],
       [39.05942 ],
       [14.604175],
       [24.978724],
       [51.614986],
       [50.32141 ],
       [53.344948],
       [55.446796],
       [21.79077 ],
       [45.255592],
       [19.714092],
       [58.693607],
       [15.078915],
       [24.172396],
       [74.12882 ],
       [67.91083 ],
       [41.621136],
       [57.771923],
       [75.99149 ],
       [37.14871 ],
       [55.120075],
       [50.38027 ],
       [32.43547 ],
       [53.61244 ],
       [66.27915 ],
       [35.53208 ],
       [30.968561],
       [36.62131 ],
       [66.761246],
       [60.13549 ],
       [45.286766],
       [55.836845],
       [22.39951 ],
       [21.122372],
       [57.834507],
       [36.87373 ],
       [25.46662 ],
       [59.463818],
       [44.514126],
       [23.073553],
       [68.48177 ],
       [35.215176],
       [19.595709],
       [60.243572],
       [12.395333],
       [50.517162],
       [77.97187 ],
       [61.33987 ],
       [50.102528],
       [43.089176],
       [28.09366 ],
       [22.881157],
       [35.104023],
       [64.109276],
       [44.531643],
       [25.122986],
       [66.71339 ],
       [29.797714],
       [28.707994],
       [63.075115],
       [13.924056],
       [26.035845],
       [19.632513],
       [38.006874],
       [23.778734],
       [64.01438 ],
       [49.29484 ],
       [20.731203],
       [40.19876 ],
       [44.289326],
       [65.43179 ],
       [29.826939],
       [68.18756 ],
       [67.04567 ],
       [24.468388],
       [48.60168 ],
       [37.35001 ],
       [75.311646],
       [45.06774 ],
       [47.637486],
       [43.50562 ],
       [59.534336],
       [46.326763],
       [39.32168 ],
       [38.975567],
       [51.71603 ],
       [45.888664],
       [80.37406 ],
       [52.793964],
       [65.760994],
       [35.854164],
       [17.021566],
       [25.956503],
       [35.120853],
       [51.819843],
       [81.637535],
       [50.082928],
       [53.317028],
       [35.94872 ],
       [41.84657 ],
       [38.06015 ],
       [28.190725],
       [24.157576],
       [16.739372],
       [50.41074 ],
       [29.467829],
       [25.7638  ],
       [44.01784 ],
       [29.907747],
       [49.579967],
       [24.822296],
       [28.377092],
       [60.882206],
       [36.886005],
       [67.44116 ],
       [56.2112  ],
       [44.308216],
       [57.75071 ],
       [18.430841],
       [61.89915 ],
       [55.0621  ],
       [71.26667 ],
       [46.825794],
       [58.61101 ],
       [35.704563],
       [38.871983],
       [57.299503],
       [12.542375],
       [37.359943],
       [32.096004],
       [25.245264],
       [33.524918],
       [53.657207],
       [40.654797],
       [17.422224],
       [63.19878 ],
       [61.460835],
       [54.39464 ],
       [69.83524 ],
       [35.914196],
       [32.118645],
       [33.50454 ],
       [61.69924 ],
       [65.7261  ],
       [64.99525 ],
       [48.839   ],
       [36.031612],
       [34.483738],
       [57.55298 ],
       [31.492   ],
       [29.025854],
       [33.261333],
       [14.209234],
       [42.022266],
       [63.568604],
       [41.657055],
       [27.800987],
       [26.187342],
       [25.106836],
       [27.117983],
       [31.424257],
       [50.868   ],
       [28.627388],
       [58.469578],
       [34.690002],
       [46.004993],
       [27.653574],
       [37.32667 ],
       [57.168545],
       [24.447163],
       [38.298763],
       [18.154419],
       [33.587296],
       [49.512012]], dtype=float32)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
print("MSE:", mean_squared_error(test_y, predictions))
print("R2 Score:", r2_score(test_y, predictions))

MSE: 48.35668327508269
R2 Score: 0.8514686703718138